name: Beautiful Jekyll CI
on: [push, pull_request]

env:
  JEKYLL_PAT: ${{ secrets.PAT_KEY }}

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_KEY }}
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Setup Pages
        id: configure-pages
        uses: actions/configure-pages@v5
      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --baseurl "${{ steps.configure-pages.outputs.base_path }}" --future
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
