name: Beautiful Jekyll CI
on: [push, pull_request]

env:
  JEKYLL_PAT: ${{ secrets.PAT_KEY }}

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_KEY }}
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: bundle install && bundle exec appraisal install
      - name: Setup Pages
        id: configure-pages
        uses: actions/configure-pages@v5
      - name: Setup CI config
        run: |
          echo "---" > _config_ci.yml
          echo "baseurl: ${{ steps.configure-pages.outputs.base_path }}" >> _config_ci.yml
      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec appraisal jekyll build --future --config _config_ci.yml,_config.yml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
